### ISSUE TITLE
Input file

### ISSUE THREAD

**Issue by aremazeilles** [jamatics/pi_ctag#16]
When changeing input filename, it is good to maintain updated:

* the readme file, in the usage section (and launch the docker image)
* possibly the xml file indicating the test done in automatic in the github server: [test_plan.xml](https://github.com/jamatics/pi_ctag/blob/master/testdata/test_plan.xml).

The CI process fails now because I think expected files are not existing.

I took the liberty to extend the file [computePi.m](https://github.com/jamatics/pi_ctag/blob/master/balance/src/computePI.m#L63) to check the existence of the input files, and effectively, the command for the balance pi is not valid anymore:

```
./run_pi_balance testdata/input/balance.csv testdata/input/testbed_lowAssist.yaml outdir
current directory: /home/anthony/code/eurobench/pi_ctag
balance file: testdata/input/balance.csv
testbed file: testdata/input/testbed_lowAssist.yaml
result dir: outdir
Input parameters: testdata/input/balance.csv outdir
Using Octave
input subject file missing: testdata/input/testbed_lowAssist.yaml
some input parameters are invalid. Quitting
```
Looking at the input file available, I tried with file `testdata/input/subject_01_info.yaml`, and the process went well.

But the output balance file is slightly different:
```
╭─anthony@PRT0962AL ~/code/eurobench/pi_ctag ‹master*› 
╰─$ diff outdir/pi_balance.yaml testdata/output/balance/pi_balance.yaml 
2c2
< value: [394.99429, 0.13084, 0.13543, 28.90000, 0.12564, 28.23000]
---
> value: [395.12481, 0.13084, 0.13543, 28.91000, 0.12564, 28.24000]
```
Both results are very similar, could you confirm that the new one (upper line) is correct, so that I can change the one stored in the reference output folder?

I got also similar issue with the metabolic cost. The call in the readme is:
```
./run_pi_metabolicCost testdata/input/chrono.csv testdata/input/testbed_lowAssist_metaboliccost.yaml outdir
```
But file `testbed_lowAssist_metaboliccost.yaml`doe snot exist anymore. The `subject_01_info.yaml` does not seem to be the good one, as `load` is missing in it. The only file containing `load` tag is `condition.yaml`, but the tag `subject_weight` is then not present.
Could you have a look at this?

Thanks

**Comment by jamatics** [comment]
@aremazeilles The output looks to be correct. So you can go with upper_line values. 
I have briefly looked at the main readme file and it looks incomplete. I am on it will add more details in the next few days. But before doing so I want to cross-verify that all the input and the code is generating the correct results. I fix the problem with the metabolic cost PI. Now the result is a bit different for the second result value because I have verified that the chrono.csv file is not the same as was used to generate the output results back in May 2020. Anyways, now MetabolicCost is fixed. I on the task of correcting the ReadMe files and verification of the code. I will let you know in the next few days for cross-checking. Thanks, Jawad

**Comment by aremazeilles** [comment]
ping

**Comment by jamatics** [comment]
@aremazeilles Please take a look if the test_plan.xml is generating the similar errors or not. Thanks.

**Comment by jamatics** [comment]
I think the issue is resolved. Please verify and close this issue.

**Comment by aremazeilles** [comment]
Sounds good indeed, thanks !
